log:
  loglevel: "ERROR"
  logpath:

server:
  httpserver:
    name: "connect"
    serial: 1
    addr: "0.0.0.0"
    port: 18075
    register: "http://127.0.0.1:18075"

register:
  healthyrolltime: 3000
  etcd:
    cluster:
      - "http://127.0.0.1:23791"

cache:
  redis:
    maincache:
      addr: "localhost:26379"
      password: "123456"
      db: 9

rpc:
  cert:
    client:
      clientcertfile: "cert/server.pem"
  subservers:
    accountdaoserver: "account-dao"
    imdaoserver: "im-dao"
    spacedaoserver: "space-dao"
    livedaoserver: "live-dao"

messagequeue:
  consumetopics:
    websocketnotify:
      topic: "websocket_notify"
      channel: "websocket_notify_channel"
  nsq:
    cluster: "127.0.0.1:4150"

stuns:
  - "stun:stun.l.google.com:19302"
turn:
  urls:
    - ""
  username: ""
  credential: ""