log:
  loglevel: "debug"
  logpath:

server:
  addr: "localhost"
  port: 18074

client:
  spacedao:
    addr: "localhost"
    port: 18061

redis:
  redisurl: "localhost:6379"
  redispassword: "123456"
  redisdb: 9
