log:
  loglevel: "debug"
  logpath:

server:
  httpserver:
    name: "space-service"
    addr: "0.0.0.0"
    serial: 1
    port: 18074
    register: "http://127.0.0.1:18074"

register:
  healthyrolltime: 3000
  etcd:
    cluster:
      - "http://127.0.0.1:23791"

rpc:
  cert:
    client:
      clientcertfile: "cert/server.pem"
  subservers:
    accountdaoserver: "account-dao"
    shopdaoserver: "shop-dao"

messagequeue:
  publishtopics:
    websocket_notify:  "baby/websocket-notify"
  nsq:
    cluster: "127.0.0.1:4150"