log:
  loglevel: "debug"
  logpath:

server:
  name: "user-account"
  addr: "0.0.0.0"
  serial: 1
  port: 18071
  register: "http://127.0.0.1:18071"

redis:
  redisurl: "localhost:26379"
  redispassword: "123456"
  redisdb: 9

etcd:
  - "http://localhost:23791"

rpc:
  client:
    certfile: "cert/server.pem"

servers:
  accountdaoserver: "account-dao"