log:
  loglevel: "debug"
  logpath:

server:
  addr: "localhost"
  port: 18071

client:
  accountdao:
    addr: "localhost"
    port: 18061

redis:
  redisurl: "localhost:6379"
  redispassword:
  redisdb: 9
