log:
  loglevel: "debug"
  logpath: "/baby/logs/connect.log"

server:
  httpserver:
    name: "connect"
    serial: 1
    addr: "0.0.0.0"
    port: 8080
    register: "http://127.0.0.1:18075"

register:
  healthyrolltime: 3000
  etcd:
    cluster:
      - "http://etcd:2379"

rpc:
  cert:
    client:
      clientcertfile: "cert/server.pem"
  subservers:
    accountdaoserver: "account-dao"
    imdaoserver: "im-dao"
    spacedaoserver: "space-dao"

messagequeue:
  consumetopics:
    websocketnotify:
      topic: "websocket_notify"
      channel: "websocket_notify_channel"
  nsq:
    cluster: "nsq:4150"