log:
  loglevel: "ERROR"
  logpath:

server:
  httpserver:
    name: "im-service"
    serial: 1
    addr: "0.0.0.0"
    port: 18076
    register: "http://127.0.0.1:18076"

register:
  healthyrolltime: 3000
  etcd:
    cluster:
      - "http://127.0.0.1:23791"

rpc:
  cert:
    client:
      clientcertfile: "cert/server.pem"
  subservers:
    accountdaoserver: "account-dao"
    imdaoserver: "im-dao"

messagequeue:
  publishtopics:
    websocketnotify:  "websocket_notify"
  nsq:
    cluster: "127.0.0.1:4150"