log:
  loglevel: "debug"
  logpath:

server:
  httpserver:
    name: "file"
    serial: 1
    addr: "0.0.0.0"
    port: 18050
    register: "http://127.0.0.1:18050"

register:
  healthyrolltime: 3000
  etcd:
    cluster:
      - "http://127.0.0.1:23791"

messagequeue:
  consumetopics:
    deletefile:
      topic: "delete_file"
      channel: "delete_file_channel"
  nsq:
    cluster: 127.0.0.1:4150

database:
  maindatabase:
    host: 127.0.0.1
    port: 23306
    username: root
    password: 123456
    dbname: baby-file