// proto 文件版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.14.0
// source: space.proto

// 生成文件的包名

package space

import (
	common "baby-fried-rice/internal/pkg/kit/rpc/pbservices/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 空间动态添加
type ReqSpaceAddDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 操作人
	Origin string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	// 动态内容
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// 访问类型
	VisitorType int32 `protobuf:"varint,3,opt,name=visitorType,proto3" json:"visitorType,omitempty"`
}

func (x *ReqSpaceAddDao) Reset() {
	*x = ReqSpaceAddDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSpaceAddDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSpaceAddDao) ProtoMessage() {}

func (x *ReqSpaceAddDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSpaceAddDao.ProtoReflect.Descriptor instead.
func (*ReqSpaceAddDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSpaceAddDao) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ReqSpaceAddDao) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReqSpaceAddDao) GetVisitorType() int32 {
	if x != nil {
		return x.VisitorType
	}
	return 0
}

type ReqSpaceDeleteDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin string `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *ReqSpaceDeleteDao) Reset() {
	*x = ReqSpaceDeleteDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSpaceDeleteDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSpaceDeleteDao) ProtoMessage() {}

func (x *ReqSpaceDeleteDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSpaceDeleteDao.ProtoReflect.Descriptor instead.
func (*ReqSpaceDeleteDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{1}
}

func (x *ReqSpaceDeleteDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReqSpaceDeleteDao) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type ReqSpacesQueryDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonSearchReq *common.CommonSearchRequest `protobuf:"bytes,1,opt,name=commonSearchReq,proto3" json:"commonSearchReq,omitempty"`
}

func (x *ReqSpacesQueryDao) Reset() {
	*x = ReqSpacesQueryDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSpacesQueryDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSpacesQueryDao) ProtoMessage() {}

func (x *ReqSpacesQueryDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSpacesQueryDao.ProtoReflect.Descriptor instead.
func (*ReqSpacesQueryDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{2}
}

func (x *ReqSpacesQueryDao) GetCommonSearchReq() *common.CommonSearchRequest {
	if x != nil {
		return x.CommonSearchReq
	}
	return nil
}

type RspSpacesQueryDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spaces   []*SpaceQueryDao `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	Page     int64            `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64            `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *RspSpacesQueryDao) Reset() {
	*x = RspSpacesQueryDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspSpacesQueryDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspSpacesQueryDao) ProtoMessage() {}

func (x *RspSpacesQueryDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspSpacesQueryDao.ProtoReflect.Descriptor instead.
func (*RspSpacesQueryDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{3}
}

func (x *RspSpacesQueryDao) GetSpaces() []*SpaceQueryDao {
	if x != nil {
		return x.Spaces
	}
	return nil
}

func (x *RspSpacesQueryDao) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RspSpacesQueryDao) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 空间动态信息
type SpaceQueryDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 空间动态id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 空间动态发布者
	Origin string `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	// 空间动态内容
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 访问类型
	VisitorType int32 `protobuf:"varint,4,opt,name=visitorType,proto3" json:"visitorType,omitempty"`
	// 创建时间
	CreateTime string `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 空间动态其他信息
	Other *SpaceOtherDao `protobuf:"bytes,6,opt,name=other,proto3" json:"other,omitempty"`
}

func (x *SpaceQueryDao) Reset() {
	*x = SpaceQueryDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceQueryDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceQueryDao) ProtoMessage() {}

func (x *SpaceQueryDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceQueryDao.ProtoReflect.Descriptor instead.
func (*SpaceQueryDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{4}
}

func (x *SpaceQueryDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpaceQueryDao) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SpaceQueryDao) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SpaceQueryDao) GetVisitorType() int32 {
	if x != nil {
		return x.VisitorType
	}
	return 0
}

func (x *SpaceQueryDao) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *SpaceQueryDao) GetOther() *SpaceOtherDao {
	if x != nil {
		return x.Other
	}
	return nil
}

// 空间动态其他信息
type SpaceOtherDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 空间动态id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 访问量
	Visited int64 `protobuf:"varint,2,opt,name=visited,proto3" json:"visited,omitempty"`
	// 点赞数
	Liked int64 `protobuf:"varint,3,opt,name=liked,proto3" json:"liked,omitempty"`
	// 评论数
	Commented int64 `protobuf:"varint,4,opt,name=commented,proto3" json:"commented,omitempty"`
	// 点赞列表，仅显示前30条
	Likes []string `protobuf:"bytes,5,rep,name=likes,proto3" json:"likes,omitempty"`
	// 评论列表
	Comments []*SpaceCommentDao `protobuf:"bytes,6,rep,name=comments,proto3" json:"comments,omitempty"`
}

func (x *SpaceOtherDao) Reset() {
	*x = SpaceOtherDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceOtherDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceOtherDao) ProtoMessage() {}

func (x *SpaceOtherDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceOtherDao.ProtoReflect.Descriptor instead.
func (*SpaceOtherDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{5}
}

func (x *SpaceOtherDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpaceOtherDao) GetVisited() int64 {
	if x != nil {
		return x.Visited
	}
	return 0
}

func (x *SpaceOtherDao) GetLiked() int64 {
	if x != nil {
		return x.Liked
	}
	return 0
}

func (x *SpaceOtherDao) GetCommented() int64 {
	if x != nil {
		return x.Commented
	}
	return 0
}

func (x *SpaceOtherDao) GetLikes() []string {
	if x != nil {
		return x.Likes
	}
	return nil
}

func (x *SpaceOtherDao) GetComments() []*SpaceCommentDao {
	if x != nil {
		return x.Comments
	}
	return nil
}

// 空间动态操作添加
type ReqSpaceOptAddDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 空间动态或者评论操作id
	OperatorId string `protobuf:"bytes,1,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	// 空间动态id
	SpaceId string `protobuf:"bytes,2,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	// 空间动态操作对象
	OperatorObject int32 `protobuf:"varint,3,opt,name=operatorObject,proto3" json:"operatorObject,omitempty"`
	// 空间动态操作类型
	OperatorType int32 `protobuf:"varint,4,opt,name=operatorType,proto3" json:"operatorType,omitempty"`
	// 操作者
	Origin string `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *ReqSpaceOptAddDao) Reset() {
	*x = ReqSpaceOptAddDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSpaceOptAddDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSpaceOptAddDao) ProtoMessage() {}

func (x *ReqSpaceOptAddDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSpaceOptAddDao.ProtoReflect.Descriptor instead.
func (*ReqSpaceOptAddDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{6}
}

func (x *ReqSpaceOptAddDao) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *ReqSpaceOptAddDao) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ReqSpaceOptAddDao) GetOperatorObject() int32 {
	if x != nil {
		return x.OperatorObject
	}
	return 0
}

func (x *ReqSpaceOptAddDao) GetOperatorType() int32 {
	if x != nil {
		return x.OperatorType
	}
	return 0
}

func (x *ReqSpaceOptAddDao) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

// 空间动态操作取消
type ReqSpaceOptCancelDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 空间动态id
	SpaceId string `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	// 空间动态或者评论操作id
	OperatorId string `protobuf:"bytes,2,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	// 操作者
	Origin string `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *ReqSpaceOptCancelDao) Reset() {
	*x = ReqSpaceOptCancelDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSpaceOptCancelDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSpaceOptCancelDao) ProtoMessage() {}

func (x *ReqSpaceOptCancelDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSpaceOptCancelDao.ProtoReflect.Descriptor instead.
func (*ReqSpaceOptCancelDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{7}
}

func (x *ReqSpaceOptCancelDao) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ReqSpaceOptCancelDao) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *ReqSpaceOptCancelDao) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

// 空间动态评论添加
type ReqSpaceCommentAddDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 空间id
	SpaceId string `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	// 上一级操作id
	ParentId string `protobuf:"bytes,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	// 评论内容
	Comment string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	// 评论类型
	CommentType int32 `protobuf:"varint,4,opt,name=commentType,proto3" json:"commentType,omitempty"`
	// 评论者
	Origin string `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *ReqSpaceCommentAddDao) Reset() {
	*x = ReqSpaceCommentAddDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSpaceCommentAddDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSpaceCommentAddDao) ProtoMessage() {}

func (x *ReqSpaceCommentAddDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSpaceCommentAddDao.ProtoReflect.Descriptor instead.
func (*ReqSpaceCommentAddDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{8}
}

func (x *ReqSpaceCommentAddDao) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ReqSpaceCommentAddDao) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ReqSpaceCommentAddDao) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ReqSpaceCommentAddDao) GetCommentType() int32 {
	if x != nil {
		return x.CommentType
	}
	return 0
}

func (x *ReqSpaceCommentAddDao) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

// 空间动态评论信息
type SpaceCommentDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 空间评论操作ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 空间id
	SpaceId string `protobuf:"bytes,2,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	// 评论内容
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 评论类型
	CommentType int32 `protobuf:"varint,4,opt,name=commentType,proto3" json:"commentType,omitempty"`
	// 评论者
	Origin string `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	// 评论时间
	CreateTime string `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 点赞人数
	Liked int64 `protobuf:"varint,7,opt,name=liked,proto3" json:"liked,omitempty"`
	// 回复列表
	ReplyList []*SpaceCommentDao `protobuf:"bytes,8,rep,name=replyList,proto3" json:"replyList,omitempty"`
}

func (x *SpaceCommentDao) Reset() {
	*x = SpaceCommentDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceCommentDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceCommentDao) ProtoMessage() {}

func (x *SpaceCommentDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceCommentDao.ProtoReflect.Descriptor instead.
func (*SpaceCommentDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{9}
}

func (x *SpaceCommentDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpaceCommentDao) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *SpaceCommentDao) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SpaceCommentDao) GetCommentType() int32 {
	if x != nil {
		return x.CommentType
	}
	return 0
}

func (x *SpaceCommentDao) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SpaceCommentDao) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *SpaceCommentDao) GetLiked() int64 {
	if x != nil {
		return x.Liked
	}
	return 0
}

func (x *SpaceCommentDao) GetReplyList() []*SpaceCommentDao {
	if x != nil {
		return x.ReplyList
	}
	return nil
}

// 空间动态评论删除
type ReqSpaceCommentDeleteDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 评论id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 空间id
	SpaceId string `protobuf:"bytes,2,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	// 操作者
	Origin string `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *ReqSpaceCommentDeleteDao) Reset() {
	*x = ReqSpaceCommentDeleteDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSpaceCommentDeleteDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSpaceCommentDeleteDao) ProtoMessage() {}

func (x *ReqSpaceCommentDeleteDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSpaceCommentDeleteDao.ProtoReflect.Descriptor instead.
func (*ReqSpaceCommentDeleteDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{10}
}

func (x *ReqSpaceCommentDeleteDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReqSpaceCommentDeleteDao) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ReqSpaceCommentDeleteDao) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

var File_space_proto protoreflect.FileDescriptor

var file_space_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64,
	0x0a, 0x0e, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x41, 0x64, 0x64, 0x44, 0x61, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x3b, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x22, 0x5a, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x12, 0x45, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x22, 0x70, 0x0a,
	0x11, 0x52, 0x73, 0x70, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44,
	0x61, 0x6f, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x52, 0x06, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0xbe, 0x01, 0x0a, 0x0d, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x44, 0x61, 0x6f, 0x52, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x22, 0xb6, 0x01, 0x0a, 0x0d, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x44,
	0x61, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6b, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6b,
	0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x6f, 0x52,
	0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xb1, 0x01, 0x0a, 0x11, 0x52, 0x65,
	0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x41, 0x64, 0x64, 0x44, 0x61, 0x6f, 0x12,
	0x1e, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x22, 0x68, 0x0a,
	0x14, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x44, 0x61, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x22, 0xa1, 0x01, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x44, 0x61,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x22, 0xfa, 0x01, 0x0a, 0x0f,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6b, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69,
	0x6b, 0x65, 0x64, 0x12, 0x33, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x6f, 0x52, 0x09, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x61, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x32, 0xf6, 0x03, 0x0a, 0x08, 0x44, 0x61, 0x6f, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x53, 0x70, 0x61, 0x63, 0x65, 0x41, 0x64, 0x64, 0x44,
	0x61, 0x6f, 0x12, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x41, 0x64, 0x64, 0x44, 0x61, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x41, 0x0a, 0x0e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x61, 0x6f, 0x12, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x42, 0x0a, 0x0e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x44, 0x61, 0x6f, 0x12, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x1a, 0x17,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x73, 0x70, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x12, 0x41, 0x0a, 0x0e, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x4f, 0x70, 0x74, 0x41, 0x64, 0x64, 0x44, 0x61, 0x6f, 0x12, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x41, 0x64, 0x64, 0x44,
	0x61, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x47, 0x0a, 0x11, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x44, 0x61, 0x6f, 0x12,
	0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4f,
	0x70, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x44, 0x61, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x49, 0x0a, 0x12, 0x53, 0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x44, 0x61, 0x6f, 0x12, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x41, 0x64, 0x64, 0x44, 0x61, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4f,
	0x0a, 0x15, 0x53, 0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x12, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42,
	0x37, 0x5a, 0x35, 0x62, 0x61, 0x62, 0x79, 0x2d, 0x66, 0x72, 0x69, 0x65, 0x64, 0x2d, 0x72, 0x69,
	0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x6b, 0x69, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_space_proto_rawDescOnce sync.Once
	file_space_proto_rawDescData = file_space_proto_rawDesc
)

func file_space_proto_rawDescGZIP() []byte {
	file_space_proto_rawDescOnce.Do(func() {
		file_space_proto_rawDescData = protoimpl.X.CompressGZIP(file_space_proto_rawDescData)
	})
	return file_space_proto_rawDescData
}

var file_space_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_space_proto_goTypes = []interface{}{
	(*ReqSpaceAddDao)(nil),             // 0: user.ReqSpaceAddDao
	(*ReqSpaceDeleteDao)(nil),          // 1: user.ReqSpaceDeleteDao
	(*ReqSpacesQueryDao)(nil),          // 2: user.ReqSpacesQueryDao
	(*RspSpacesQueryDao)(nil),          // 3: user.RspSpacesQueryDao
	(*SpaceQueryDao)(nil),              // 4: user.SpaceQueryDao
	(*SpaceOtherDao)(nil),              // 5: user.SpaceOtherDao
	(*ReqSpaceOptAddDao)(nil),          // 6: user.ReqSpaceOptAddDao
	(*ReqSpaceOptCancelDao)(nil),       // 7: user.ReqSpaceOptCancelDao
	(*ReqSpaceCommentAddDao)(nil),      // 8: user.ReqSpaceCommentAddDao
	(*SpaceCommentDao)(nil),            // 9: user.SpaceCommentDao
	(*ReqSpaceCommentDeleteDao)(nil),   // 10: user.ReqSpaceCommentDeleteDao
	(*common.CommonSearchRequest)(nil), // 11: common.CommonSearchRequest
	(*emptypb.Empty)(nil),              // 12: google.protobuf.Empty
}
var file_space_proto_depIdxs = []int32{
	11, // 0: user.ReqSpacesQueryDao.commonSearchReq:type_name -> common.CommonSearchRequest
	4,  // 1: user.RspSpacesQueryDao.spaces:type_name -> user.SpaceQueryDao
	5,  // 2: user.SpaceQueryDao.other:type_name -> user.SpaceOtherDao
	9,  // 3: user.SpaceOtherDao.comments:type_name -> user.SpaceCommentDao
	9,  // 4: user.SpaceCommentDao.replyList:type_name -> user.SpaceCommentDao
	0,  // 5: user.DaoSpace.SpaceAddDao:input_type -> user.ReqSpaceAddDao
	1,  // 6: user.DaoSpace.SpaceDeleteDao:input_type -> user.ReqSpaceDeleteDao
	2,  // 7: user.DaoSpace.SpacesQueryDao:input_type -> user.ReqSpacesQueryDao
	6,  // 8: user.DaoSpace.SpaceOptAddDao:input_type -> user.ReqSpaceOptAddDao
	7,  // 9: user.DaoSpace.SpaceOptCancelDao:input_type -> user.ReqSpaceOptCancelDao
	8,  // 10: user.DaoSpace.SpaceCommentAddDao:input_type -> user.ReqSpaceCommentAddDao
	10, // 11: user.DaoSpace.SpaceCommentDeleteDao:input_type -> user.ReqSpaceCommentDeleteDao
	12, // 12: user.DaoSpace.SpaceAddDao:output_type -> google.protobuf.Empty
	12, // 13: user.DaoSpace.SpaceDeleteDao:output_type -> google.protobuf.Empty
	3,  // 14: user.DaoSpace.SpacesQueryDao:output_type -> user.RspSpacesQueryDao
	12, // 15: user.DaoSpace.SpaceOptAddDao:output_type -> google.protobuf.Empty
	12, // 16: user.DaoSpace.SpaceOptCancelDao:output_type -> google.protobuf.Empty
	12, // 17: user.DaoSpace.SpaceCommentAddDao:output_type -> google.protobuf.Empty
	12, // 18: user.DaoSpace.SpaceCommentDeleteDao:output_type -> google.protobuf.Empty
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_space_proto_init() }
func file_space_proto_init() {
	if File_space_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_space_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSpaceAddDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSpaceDeleteDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSpacesQueryDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspSpacesQueryDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceQueryDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceOtherDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSpaceOptAddDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSpaceOptCancelDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSpaceCommentAddDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceCommentDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSpaceCommentDeleteDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_space_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_space_proto_goTypes,
		DependencyIndexes: file_space_proto_depIdxs,
		MessageInfos:      file_space_proto_msgTypes,
	}.Build()
	File_space_proto = out.File
	file_space_proto_rawDesc = nil
	file_space_proto_goTypes = nil
	file_space_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DaoSpaceClient is the client API for DaoSpace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaoSpaceClient interface {
	// 空间动态添加
	SpaceAddDao(ctx context.Context, in *ReqSpaceAddDao, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 空间动态删除
	SpaceDeleteDao(ctx context.Context, in *ReqSpaceDeleteDao, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 空间动态查询
	SpacesQueryDao(ctx context.Context, in *ReqSpacesQueryDao, opts ...grpc.CallOption) (*RspSpacesQueryDao, error)
	// 空间动态操作添加
	SpaceOptAddDao(ctx context.Context, in *ReqSpaceOptAddDao, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 空间动态操作取消
	SpaceOptCancelDao(ctx context.Context, in *ReqSpaceOptCancelDao, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 空间动态评论添加
	SpaceCommentAddDao(ctx context.Context, in *ReqSpaceCommentAddDao, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 空间动态评论删除
	SpaceCommentDeleteDao(ctx context.Context, in *ReqSpaceCommentDeleteDao, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type daoSpaceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaoSpaceClient(cc grpc.ClientConnInterface) DaoSpaceClient {
	return &daoSpaceClient{cc}
}

func (c *daoSpaceClient) SpaceAddDao(ctx context.Context, in *ReqSpaceAddDao, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/user.DaoSpace/SpaceAddDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoSpaceClient) SpaceDeleteDao(ctx context.Context, in *ReqSpaceDeleteDao, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/user.DaoSpace/SpaceDeleteDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoSpaceClient) SpacesQueryDao(ctx context.Context, in *ReqSpacesQueryDao, opts ...grpc.CallOption) (*RspSpacesQueryDao, error) {
	out := new(RspSpacesQueryDao)
	err := c.cc.Invoke(ctx, "/user.DaoSpace/SpacesQueryDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoSpaceClient) SpaceOptAddDao(ctx context.Context, in *ReqSpaceOptAddDao, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/user.DaoSpace/SpaceOptAddDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoSpaceClient) SpaceOptCancelDao(ctx context.Context, in *ReqSpaceOptCancelDao, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/user.DaoSpace/SpaceOptCancelDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoSpaceClient) SpaceCommentAddDao(ctx context.Context, in *ReqSpaceCommentAddDao, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/user.DaoSpace/SpaceCommentAddDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoSpaceClient) SpaceCommentDeleteDao(ctx context.Context, in *ReqSpaceCommentDeleteDao, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/user.DaoSpace/SpaceCommentDeleteDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaoSpaceServer is the server API for DaoSpace service.
type DaoSpaceServer interface {
	// 空间动态添加
	SpaceAddDao(context.Context, *ReqSpaceAddDao) (*emptypb.Empty, error)
	// 空间动态删除
	SpaceDeleteDao(context.Context, *ReqSpaceDeleteDao) (*emptypb.Empty, error)
	// 空间动态查询
	SpacesQueryDao(context.Context, *ReqSpacesQueryDao) (*RspSpacesQueryDao, error)
	// 空间动态操作添加
	SpaceOptAddDao(context.Context, *ReqSpaceOptAddDao) (*emptypb.Empty, error)
	// 空间动态操作取消
	SpaceOptCancelDao(context.Context, *ReqSpaceOptCancelDao) (*emptypb.Empty, error)
	// 空间动态评论添加
	SpaceCommentAddDao(context.Context, *ReqSpaceCommentAddDao) (*emptypb.Empty, error)
	// 空间动态评论删除
	SpaceCommentDeleteDao(context.Context, *ReqSpaceCommentDeleteDao) (*emptypb.Empty, error)
}

// UnimplementedDaoSpaceServer can be embedded to have forward compatible implementations.
type UnimplementedDaoSpaceServer struct {
}

func (*UnimplementedDaoSpaceServer) SpaceAddDao(context.Context, *ReqSpaceAddDao) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpaceAddDao not implemented")
}
func (*UnimplementedDaoSpaceServer) SpaceDeleteDao(context.Context, *ReqSpaceDeleteDao) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpaceDeleteDao not implemented")
}
func (*UnimplementedDaoSpaceServer) SpacesQueryDao(context.Context, *ReqSpacesQueryDao) (*RspSpacesQueryDao, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpacesQueryDao not implemented")
}
func (*UnimplementedDaoSpaceServer) SpaceOptAddDao(context.Context, *ReqSpaceOptAddDao) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpaceOptAddDao not implemented")
}
func (*UnimplementedDaoSpaceServer) SpaceOptCancelDao(context.Context, *ReqSpaceOptCancelDao) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpaceOptCancelDao not implemented")
}
func (*UnimplementedDaoSpaceServer) SpaceCommentAddDao(context.Context, *ReqSpaceCommentAddDao) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpaceCommentAddDao not implemented")
}
func (*UnimplementedDaoSpaceServer) SpaceCommentDeleteDao(context.Context, *ReqSpaceCommentDeleteDao) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpaceCommentDeleteDao not implemented")
}

func RegisterDaoSpaceServer(s *grpc.Server, srv DaoSpaceServer) {
	s.RegisterService(&_DaoSpace_serviceDesc, srv)
}

func _DaoSpace_SpaceAddDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSpaceAddDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoSpaceServer).SpaceAddDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoSpace/SpaceAddDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoSpaceServer).SpaceAddDao(ctx, req.(*ReqSpaceAddDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoSpace_SpaceDeleteDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSpaceDeleteDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoSpaceServer).SpaceDeleteDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoSpace/SpaceDeleteDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoSpaceServer).SpaceDeleteDao(ctx, req.(*ReqSpaceDeleteDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoSpace_SpacesQueryDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSpacesQueryDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoSpaceServer).SpacesQueryDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoSpace/SpacesQueryDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoSpaceServer).SpacesQueryDao(ctx, req.(*ReqSpacesQueryDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoSpace_SpaceOptAddDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSpaceOptAddDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoSpaceServer).SpaceOptAddDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoSpace/SpaceOptAddDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoSpaceServer).SpaceOptAddDao(ctx, req.(*ReqSpaceOptAddDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoSpace_SpaceOptCancelDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSpaceOptCancelDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoSpaceServer).SpaceOptCancelDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoSpace/SpaceOptCancelDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoSpaceServer).SpaceOptCancelDao(ctx, req.(*ReqSpaceOptCancelDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoSpace_SpaceCommentAddDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSpaceCommentAddDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoSpaceServer).SpaceCommentAddDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoSpace/SpaceCommentAddDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoSpaceServer).SpaceCommentAddDao(ctx, req.(*ReqSpaceCommentAddDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoSpace_SpaceCommentDeleteDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSpaceCommentDeleteDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoSpaceServer).SpaceCommentDeleteDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoSpace/SpaceCommentDeleteDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoSpaceServer).SpaceCommentDeleteDao(ctx, req.(*ReqSpaceCommentDeleteDao))
	}
	return interceptor(ctx, in, info, handler)
}

var _DaoSpace_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.DaoSpace",
	HandlerType: (*DaoSpaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpaceAddDao",
			Handler:    _DaoSpace_SpaceAddDao_Handler,
		},
		{
			MethodName: "SpaceDeleteDao",
			Handler:    _DaoSpace_SpaceDeleteDao_Handler,
		},
		{
			MethodName: "SpacesQueryDao",
			Handler:    _DaoSpace_SpacesQueryDao_Handler,
		},
		{
			MethodName: "SpaceOptAddDao",
			Handler:    _DaoSpace_SpaceOptAddDao_Handler,
		},
		{
			MethodName: "SpaceOptCancelDao",
			Handler:    _DaoSpace_SpaceOptCancelDao_Handler,
		},
		{
			MethodName: "SpaceCommentAddDao",
			Handler:    _DaoSpace_SpaceCommentAddDao_Handler,
		},
		{
			MethodName: "SpaceCommentDeleteDao",
			Handler:    _DaoSpace_SpaceCommentDeleteDao_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "space.proto",
}
