// proto 文件版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.14.0
// source: space.proto

// 生成文件的包名

package space

import (
	common "baby-fried-rice/internal/pkg/kit/rpc/pbservices/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqSpaceAddDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin      string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Content     string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	VisitorType int32  `protobuf:"varint,3,opt,name=visitorType,proto3" json:"visitorType,omitempty"`
}

func (x *ReqSpaceAddDao) Reset() {
	*x = ReqSpaceAddDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSpaceAddDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSpaceAddDao) ProtoMessage() {}

func (x *ReqSpaceAddDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSpaceAddDao.ProtoReflect.Descriptor instead.
func (*ReqSpaceAddDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSpaceAddDao) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ReqSpaceAddDao) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReqSpaceAddDao) GetVisitorType() int32 {
	if x != nil {
		return x.VisitorType
	}
	return 0
}

type ReqSpaceDeleteDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReqSpaceDeleteDao) Reset() {
	*x = ReqSpaceDeleteDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSpaceDeleteDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSpaceDeleteDao) ProtoMessage() {}

func (x *ReqSpaceDeleteDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSpaceDeleteDao.ProtoReflect.Descriptor instead.
func (*ReqSpaceDeleteDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{1}
}

func (x *ReqSpaceDeleteDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReqSpacesQueryDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonSearchReq *common.CommonSearchRequest `protobuf:"bytes,1,opt,name=commonSearchReq,proto3" json:"commonSearchReq,omitempty"`
}

func (x *ReqSpacesQueryDao) Reset() {
	*x = ReqSpacesQueryDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSpacesQueryDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSpacesQueryDao) ProtoMessage() {}

func (x *ReqSpacesQueryDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSpacesQueryDao.ProtoReflect.Descriptor instead.
func (*ReqSpacesQueryDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{2}
}

func (x *ReqSpacesQueryDao) GetCommonSearchReq() *common.CommonSearchRequest {
	if x != nil {
		return x.CommonSearchReq
	}
	return nil
}

type RspSpacesQueryDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*SpaceQueryDao `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *RspSpacesQueryDao) Reset() {
	*x = RspSpacesQueryDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspSpacesQueryDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspSpacesQueryDao) ProtoMessage() {}

func (x *RspSpacesQueryDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspSpacesQueryDao.ProtoReflect.Descriptor instead.
func (*RspSpacesQueryDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{3}
}

func (x *RspSpacesQueryDao) GetList() []*SpaceQueryDao {
	if x != nil {
		return x.List
	}
	return nil
}

type SpaceQueryDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin      string         `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Content     string         `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	VisitorType int32          `protobuf:"varint,4,opt,name=visitorType,proto3" json:"visitorType,omitempty"`
	CreateTime  string         `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Other       *SpaceQueryDao `protobuf:"bytes,6,opt,name=other,proto3" json:"other,omitempty"`
}

func (x *SpaceQueryDao) Reset() {
	*x = SpaceQueryDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceQueryDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceQueryDao) ProtoMessage() {}

func (x *SpaceQueryDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceQueryDao.ProtoReflect.Descriptor instead.
func (*SpaceQueryDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{4}
}

func (x *SpaceQueryDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpaceQueryDao) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SpaceQueryDao) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SpaceQueryDao) GetVisitorType() int32 {
	if x != nil {
		return x.VisitorType
	}
	return 0
}

func (x *SpaceQueryDao) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *SpaceQueryDao) GetOther() *SpaceQueryDao {
	if x != nil {
		return x.Other
	}
	return nil
}

type SpaceOtherDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Visited int64  `protobuf:"varint,2,opt,name=visited,proto3" json:"visited,omitempty"`
}

func (x *SpaceOtherDao) Reset() {
	*x = SpaceOtherDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceOtherDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceOtherDao) ProtoMessage() {}

func (x *SpaceOtherDao) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceOtherDao.ProtoReflect.Descriptor instead.
func (*SpaceOtherDao) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{5}
}

func (x *SpaceOtherDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpaceOtherDao) GetVisited() int64 {
	if x != nil {
		return x.Visited
	}
	return 0
}

var File_space_proto protoreflect.FileDescriptor

var file_space_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64,
	0x0a, 0x0e, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x41, 0x64, 0x64, 0x44, 0x61, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5a, 0x0a, 0x11, 0x52, 0x65, 0x71,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x12, 0x45,
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x22, 0x3c, 0x0a, 0x11, 0x52, 0x73, 0x70, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0xbe, 0x01, 0x0a, 0x0d, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x44, 0x61, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x69, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x76, 0x69,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x52, 0x05, 0x6f,
	0x74, 0x68, 0x65, 0x72, 0x22, 0x39, 0x0a, 0x0d, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4f, 0x74, 0x68,
	0x65, 0x72, 0x44, 0x61, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x32,
	0xce, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x6f, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0b,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x41, 0x64, 0x64, 0x44, 0x61, 0x6f, 0x12, 0x14, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x41, 0x64, 0x64, 0x44, 0x61,
	0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x41, 0x0a, 0x0e, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x12, 0x17, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x61, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x42, 0x0a, 0x0e,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x12, 0x17,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x1a, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52,
	0x73, 0x70, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f,
	0x42, 0x37, 0x5a, 0x35, 0x62, 0x61, 0x62, 0x79, 0x2d, 0x66, 0x72, 0x69, 0x65, 0x64, 0x2d, 0x72,
	0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x6b, 0x69, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_space_proto_rawDescOnce sync.Once
	file_space_proto_rawDescData = file_space_proto_rawDesc
)

func file_space_proto_rawDescGZIP() []byte {
	file_space_proto_rawDescOnce.Do(func() {
		file_space_proto_rawDescData = protoimpl.X.CompressGZIP(file_space_proto_rawDescData)
	})
	return file_space_proto_rawDescData
}

var file_space_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_space_proto_goTypes = []interface{}{
	(*ReqSpaceAddDao)(nil),             // 0: user.ReqSpaceAddDao
	(*ReqSpaceDeleteDao)(nil),          // 1: user.ReqSpaceDeleteDao
	(*ReqSpacesQueryDao)(nil),          // 2: user.ReqSpacesQueryDao
	(*RspSpacesQueryDao)(nil),          // 3: user.RspSpacesQueryDao
	(*SpaceQueryDao)(nil),              // 4: user.SpaceQueryDao
	(*SpaceOtherDao)(nil),              // 5: user.SpaceOtherDao
	(*common.CommonSearchRequest)(nil), // 6: common.CommonSearchRequest
	(*emptypb.Empty)(nil),              // 7: google.protobuf.Empty
}
var file_space_proto_depIdxs = []int32{
	6, // 0: user.ReqSpacesQueryDao.commonSearchReq:type_name -> common.CommonSearchRequest
	4, // 1: user.RspSpacesQueryDao.list:type_name -> user.SpaceQueryDao
	4, // 2: user.SpaceQueryDao.other:type_name -> user.SpaceQueryDao
	0, // 3: user.DaoSpace.SpaceAddDao:input_type -> user.ReqSpaceAddDao
	1, // 4: user.DaoSpace.SpaceDeleteDao:input_type -> user.ReqSpaceDeleteDao
	2, // 5: user.DaoSpace.SpacesQueryDao:input_type -> user.ReqSpacesQueryDao
	7, // 6: user.DaoSpace.SpaceAddDao:output_type -> google.protobuf.Empty
	7, // 7: user.DaoSpace.SpaceDeleteDao:output_type -> google.protobuf.Empty
	3, // 8: user.DaoSpace.SpacesQueryDao:output_type -> user.RspSpacesQueryDao
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_space_proto_init() }
func file_space_proto_init() {
	if File_space_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_space_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSpaceAddDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSpaceDeleteDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSpacesQueryDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspSpacesQueryDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceQueryDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceOtherDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_space_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_space_proto_goTypes,
		DependencyIndexes: file_space_proto_depIdxs,
		MessageInfos:      file_space_proto_msgTypes,
	}.Build()
	File_space_proto = out.File
	file_space_proto_rawDesc = nil
	file_space_proto_goTypes = nil
	file_space_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DaoSpaceClient is the client API for DaoSpace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaoSpaceClient interface {
	// 空间动态添加
	SpaceAddDao(ctx context.Context, in *ReqSpaceAddDao, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 空间动态删除
	SpaceDeleteDao(ctx context.Context, in *ReqSpaceDeleteDao, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 空间动态查询
	SpacesQueryDao(ctx context.Context, in *ReqSpacesQueryDao, opts ...grpc.CallOption) (*RspSpacesQueryDao, error)
}

type daoSpaceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaoSpaceClient(cc grpc.ClientConnInterface) DaoSpaceClient {
	return &daoSpaceClient{cc}
}

func (c *daoSpaceClient) SpaceAddDao(ctx context.Context, in *ReqSpaceAddDao, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/user.DaoSpace/SpaceAddDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoSpaceClient) SpaceDeleteDao(ctx context.Context, in *ReqSpaceDeleteDao, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/user.DaoSpace/SpaceDeleteDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoSpaceClient) SpacesQueryDao(ctx context.Context, in *ReqSpacesQueryDao, opts ...grpc.CallOption) (*RspSpacesQueryDao, error) {
	out := new(RspSpacesQueryDao)
	err := c.cc.Invoke(ctx, "/user.DaoSpace/SpacesQueryDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaoSpaceServer is the server API for DaoSpace service.
type DaoSpaceServer interface {
	// 空间动态添加
	SpaceAddDao(context.Context, *ReqSpaceAddDao) (*emptypb.Empty, error)
	// 空间动态删除
	SpaceDeleteDao(context.Context, *ReqSpaceDeleteDao) (*emptypb.Empty, error)
	// 空间动态查询
	SpacesQueryDao(context.Context, *ReqSpacesQueryDao) (*RspSpacesQueryDao, error)
}

// UnimplementedDaoSpaceServer can be embedded to have forward compatible implementations.
type UnimplementedDaoSpaceServer struct {
}

func (*UnimplementedDaoSpaceServer) SpaceAddDao(context.Context, *ReqSpaceAddDao) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpaceAddDao not implemented")
}
func (*UnimplementedDaoSpaceServer) SpaceDeleteDao(context.Context, *ReqSpaceDeleteDao) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpaceDeleteDao not implemented")
}
func (*UnimplementedDaoSpaceServer) SpacesQueryDao(context.Context, *ReqSpacesQueryDao) (*RspSpacesQueryDao, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpacesQueryDao not implemented")
}

func RegisterDaoSpaceServer(s *grpc.Server, srv DaoSpaceServer) {
	s.RegisterService(&_DaoSpace_serviceDesc, srv)
}

func _DaoSpace_SpaceAddDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSpaceAddDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoSpaceServer).SpaceAddDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoSpace/SpaceAddDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoSpaceServer).SpaceAddDao(ctx, req.(*ReqSpaceAddDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoSpace_SpaceDeleteDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSpaceDeleteDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoSpaceServer).SpaceDeleteDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoSpace/SpaceDeleteDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoSpaceServer).SpaceDeleteDao(ctx, req.(*ReqSpaceDeleteDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoSpace_SpacesQueryDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSpacesQueryDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoSpaceServer).SpacesQueryDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoSpace/SpacesQueryDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoSpaceServer).SpacesQueryDao(ctx, req.(*ReqSpacesQueryDao))
	}
	return interceptor(ctx, in, info, handler)
}

var _DaoSpace_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.DaoSpace",
	HandlerType: (*DaoSpaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpaceAddDao",
			Handler:    _DaoSpace_SpaceAddDao_Handler,
		},
		{
			MethodName: "SpaceDeleteDao",
			Handler:    _DaoSpace_SpaceDeleteDao_Handler,
		},
		{
			MethodName: "SpacesQueryDao",
			Handler:    _DaoSpace_SpacesQueryDao_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "space.proto",
}
