version: "3"
services:
  redis:
    image: redis:latest
    container_name: baby-redis
    restart: always
    ports:
      - "26379:6379"
    volumes:
      - "./config/redis.conf:/etc/redis/redis.conf:rw"
      - "./data/redis:/data:rw"
    command:
      redis-server /etc/redis/redis.conf --appendonly yes
  mysql:
    image: mysql:5.7
    container_name: baby-mysql
    restart: always
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "./data/db:/var/lib/mysql"
      - "./init:/docker-entrypoint-initdb.d/"
  etcd:
    image: quay.io/coreos/etcd:v3.3.12
    container_name: etcd
    ports:
      - "23791:2379"
      - "2380"
    environment:
      ETCDCTL_API: 3
    volumes:
      - "./data/etcd/etcd-data:/etcd-data"
    command:
      - "/usr/local/bin/etcd"
      - "--name"
      - "s1"
      - "--data-dir"
      - "/etcd-data"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - --listen-client-urls
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://0.0.0.0:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "tkn"
      - "--initial-cluster"
      - "s1=http://0.0.0.0:2380"
      - "--initial-cluster-state"
      - "new"
  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    restart: always
    ports:
      - 4160:4160
      - 4161:4161
    command: /nsqlookupd
  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    restart: always
    ports:
      - 4171:4171
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    restart: always
    ports:
      - 4150:4150
      - 4151:4151
    volumes:
      - "./data/nsq:/usr/local/nsq/bin/data"
    command: /nsqd --broadcast-address=172.16.29.129 --lookupd-tcp-address=nsqlookupd:4160
  baby-gateway:
    image: baby-gateway
    container_name: baby-gateway
    ports:
      - "18070:8080"
    volumes:
      - "./cmd/gateway/res:/go/src/baby-fried-rice/module/gateway/res"
      - "./cmd/gateway/logs:/baby/logs"
    restart: always
    depends_on:
      - redis
      - etcd
  baby-account-dao:
    image: baby-account-dao
    container_name: baby-account-dao
    ports:
      - "18061:8080"
    volumes:
      - "./cmd/accountDao/res:/go/src/baby-fried-rice/module/accountDao/res"
      - "./cmd/accountDao/logs:/baby/logs"
    restart: always
    depends_on:
      - mysql
      - redis
      - etcd
  baby-user-account:
    image: baby-user-account
    container_name: baby-user-account
    ports:
      - "18071:8080"
    volumes:
      - "./cmd/userAccount/res:/go/src/baby-fried-rice/module/userAccount/res"
      - "./cmd/userAccount/logs:/baby/logs"
    restart: always
    depends_on:
      - baby-account-dao
      - etcd
  baby-space-dao:
    image: baby-space-dao
    container_name: baby-space-dao
    ports:
      - "18062:8080"
    volumes:
      - "./cmd/spaceDao/res:/go/src/baby-fried-rice/module/spaceDao/res"
      - "./cmd/spaceDao/logs:/baby/logs"
    restart: always
    depends_on:
      - mysql
      - etcd
  baby-space:
    image: baby-space
    container_name: baby-space
    ports:
      - "18074:8080"
    volumes:
      - "./cmd/space/res:/go/src/baby-fried-rice/module/space/res"
      - "./cmd/space/logs:/baby/logs"
    restart: always
    depends_on:
      - baby-space-dao
      - etcd
      - nsqd
  baby-im-dao:
    image: baby-im-dao
    container_name: baby-im-dao
    ports:
      - "18063:8080"
    volumes:
      - "./cmd/imDao/res:/go/src/baby-fried-rice/module/imDao/res"
      - "./cmd/imDao/logs:/baby/logs"
    restart: always
    depends_on:
      - mysql
      - etcd
  baby-im:
    image: baby-im
    container_name: baby-im
    ports:
      - "18076:8080"
    volumes:
      - "./cmd/im/res:/go/src/baby-fried-rice/module/im/res"
      - "./cmd/im/logs:/baby/logs"
    restart: always
    depends_on:
      - baby-im-dao
      - etcd
  baby-connect:
    image: baby-connect
    container_name: baby-connect
    ports:
      - "18075:8080"
    volumes:
      - "./cmd/connect/res:/go/src/baby-fried-rice/module/connect/res"
      - "./cmd/connect/logs:/baby/logs"
    restart: always
    depends_on:
      - nsqd
      - etcd
  baby-file:
    image: baby-file
    container_name: baby-file
    ports:
      - "18050:8080"
    volumes:
      - "./cmd/file/res:/go/src/baby-fried-rice/module/file/res"
      - "./cmd/file/logs:/baby/logs"
    restart: always
    depends_on:
      - mysql
      - etcd