// proto 文件版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.14.0
// source: privatemessage.proto

// 生成文件的包名

package privatemessage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqPrivateMessageAddDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 发送者
	SendId string `protobuf:"bytes,1,opt,name=sendId,proto3" json:"sendId,omitempty"`
	// 接受者
	ReceiveId string `protobuf:"bytes,2,opt,name=receiveId,proto3" json:"receiveId,omitempty"`
	// 消息类型
	MessageType int32 `protobuf:"varint,3,opt,name=messageType,proto3" json:"messageType,omitempty"`
	// 消息发送类型
	MessageSendType int32 `protobuf:"varint,4,opt,name=messageSendType,proto3" json:"messageSendType,omitempty"`
	// 标题
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// 内容
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	// 时间
	CreateTimestamp int64 `protobuf:"varint,7,opt,name=createTimestamp,proto3" json:"createTimestamp,omitempty"`
}

func (x *ReqPrivateMessageAddDao) Reset() {
	*x = ReqPrivateMessageAddDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privatemessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPrivateMessageAddDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPrivateMessageAddDao) ProtoMessage() {}

func (x *ReqPrivateMessageAddDao) ProtoReflect() protoreflect.Message {
	mi := &file_privatemessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPrivateMessageAddDao.ProtoReflect.Descriptor instead.
func (*ReqPrivateMessageAddDao) Descriptor() ([]byte, []int) {
	return file_privatemessage_proto_rawDescGZIP(), []int{0}
}

func (x *ReqPrivateMessageAddDao) GetSendId() string {
	if x != nil {
		return x.SendId
	}
	return ""
}

func (x *ReqPrivateMessageAddDao) GetReceiveId() string {
	if x != nil {
		return x.ReceiveId
	}
	return ""
}

func (x *ReqPrivateMessageAddDao) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *ReqPrivateMessageAddDao) GetMessageSendType() int32 {
	if x != nil {
		return x.MessageSendType
	}
	return 0
}

func (x *ReqPrivateMessageAddDao) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReqPrivateMessageAddDao) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReqPrivateMessageAddDao) GetCreateTimestamp() int64 {
	if x != nil {
		return x.CreateTimestamp
	}
	return 0
}

type RspPrivateMessageAddDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 私信id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RspPrivateMessageAddDao) Reset() {
	*x = RspPrivateMessageAddDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privatemessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPrivateMessageAddDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPrivateMessageAddDao) ProtoMessage() {}

func (x *RspPrivateMessageAddDao) ProtoReflect() protoreflect.Message {
	mi := &file_privatemessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPrivateMessageAddDao.ProtoReflect.Descriptor instead.
func (*RspPrivateMessageAddDao) Descriptor() ([]byte, []int) {
	return file_privatemessage_proto_rawDescGZIP(), []int{1}
}

func (x *RspPrivateMessageAddDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReqPrivateMessageDeleteDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Ids       []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ReqPrivateMessageDeleteDao) Reset() {
	*x = ReqPrivateMessageDeleteDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privatemessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPrivateMessageDeleteDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPrivateMessageDeleteDao) ProtoMessage() {}

func (x *ReqPrivateMessageDeleteDao) ProtoReflect() protoreflect.Message {
	mi := &file_privatemessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPrivateMessageDeleteDao.ProtoReflect.Descriptor instead.
func (*ReqPrivateMessageDeleteDao) Descriptor() ([]byte, []int) {
	return file_privatemessage_proto_rawDescGZIP(), []int{2}
}

func (x *ReqPrivateMessageDeleteDao) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ReqPrivateMessageDeleteDao) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ReqPrivateMessageStatusUpdateDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Ids       []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ReqPrivateMessageStatusUpdateDao) Reset() {
	*x = ReqPrivateMessageStatusUpdateDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privatemessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPrivateMessageStatusUpdateDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPrivateMessageStatusUpdateDao) ProtoMessage() {}

func (x *ReqPrivateMessageStatusUpdateDao) ProtoReflect() protoreflect.Message {
	mi := &file_privatemessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPrivateMessageStatusUpdateDao.ProtoReflect.Descriptor instead.
func (*ReqPrivateMessageStatusUpdateDao) Descriptor() ([]byte, []int) {
	return file_privatemessage_proto_rawDescGZIP(), []int{3}
}

func (x *ReqPrivateMessageStatusUpdateDao) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ReqPrivateMessageStatusUpdateDao) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ReqPrivateMessageQueryDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page            int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize        int64  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	MessageType     int32  `protobuf:"varint,3,opt,name=messageType,proto3" json:"messageType,omitempty"`
	MessageSendType int32  `protobuf:"varint,4,opt,name=messageSendType,proto3" json:"messageSendType,omitempty"`
	SendId          string `protobuf:"bytes,5,opt,name=sendId,proto3" json:"sendId,omitempty"`
	Status          uint32 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	AccountId       string `protobuf:"bytes,7,opt,name=accountId,proto3" json:"accountId,omitempty"`
}

func (x *ReqPrivateMessageQueryDao) Reset() {
	*x = ReqPrivateMessageQueryDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privatemessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPrivateMessageQueryDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPrivateMessageQueryDao) ProtoMessage() {}

func (x *ReqPrivateMessageQueryDao) ProtoReflect() protoreflect.Message {
	mi := &file_privatemessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPrivateMessageQueryDao.ProtoReflect.Descriptor instead.
func (*ReqPrivateMessageQueryDao) Descriptor() ([]byte, []int) {
	return file_privatemessage_proto_rawDescGZIP(), []int{4}
}

func (x *ReqPrivateMessageQueryDao) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ReqPrivateMessageQueryDao) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ReqPrivateMessageQueryDao) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *ReqPrivateMessageQueryDao) GetMessageSendType() int32 {
	if x != nil {
		return x.MessageSendType
	}
	return 0
}

func (x *ReqPrivateMessageQueryDao) GetSendId() string {
	if x != nil {
		return x.SendId
	}
	return ""
}

func (x *ReqPrivateMessageQueryDao) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ReqPrivateMessageQueryDao) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type RspPrivateMessageQueryDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*PrivateMessageQueryDao `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page     int64                     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64                     `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Total    int64                     `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *RspPrivateMessageQueryDao) Reset() {
	*x = RspPrivateMessageQueryDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privatemessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPrivateMessageQueryDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPrivateMessageQueryDao) ProtoMessage() {}

func (x *RspPrivateMessageQueryDao) ProtoReflect() protoreflect.Message {
	mi := &file_privatemessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPrivateMessageQueryDao.ProtoReflect.Descriptor instead.
func (*RspPrivateMessageQueryDao) Descriptor() ([]byte, []int) {
	return file_privatemessage_proto_rawDescGZIP(), []int{5}
}

func (x *RspPrivateMessageQueryDao) GetList() []*PrivateMessageQueryDao {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RspPrivateMessageQueryDao) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RspPrivateMessageQueryDao) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RspPrivateMessageQueryDao) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PrivateMessageQueryDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SendId          string `protobuf:"bytes,2,opt,name=sendId,proto3" json:"sendId,omitempty"`
	ReceiveId       string `protobuf:"bytes,3,opt,name=receiveId,proto3" json:"receiveId,omitempty"`
	MessageType     int32  `protobuf:"varint,4,opt,name=messageType,proto3" json:"messageType,omitempty"`
	MessageSendType int32  `protobuf:"varint,5,opt,name=messageSendType,proto3" json:"messageSendType,omitempty"`
	Title           string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	CreateTime      string `protobuf:"bytes,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Status          uint32 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PrivateMessageQueryDao) Reset() {
	*x = PrivateMessageQueryDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privatemessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateMessageQueryDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateMessageQueryDao) ProtoMessage() {}

func (x *PrivateMessageQueryDao) ProtoReflect() protoreflect.Message {
	mi := &file_privatemessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateMessageQueryDao.ProtoReflect.Descriptor instead.
func (*PrivateMessageQueryDao) Descriptor() ([]byte, []int) {
	return file_privatemessage_proto_rawDescGZIP(), []int{6}
}

func (x *PrivateMessageQueryDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrivateMessageQueryDao) GetSendId() string {
	if x != nil {
		return x.SendId
	}
	return ""
}

func (x *PrivateMessageQueryDao) GetReceiveId() string {
	if x != nil {
		return x.ReceiveId
	}
	return ""
}

func (x *PrivateMessageQueryDao) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *PrivateMessageQueryDao) GetMessageSendType() int32 {
	if x != nil {
		return x.MessageSendType
	}
	return 0
}

func (x *PrivateMessageQueryDao) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PrivateMessageQueryDao) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *PrivateMessageQueryDao) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ReqPrivateMessageDetailDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReqPrivateMessageDetailDao) Reset() {
	*x = ReqPrivateMessageDetailDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privatemessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPrivateMessageDetailDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPrivateMessageDetailDao) ProtoMessage() {}

func (x *ReqPrivateMessageDetailDao) ProtoReflect() protoreflect.Message {
	mi := &file_privatemessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPrivateMessageDetailDao.ProtoReflect.Descriptor instead.
func (*ReqPrivateMessageDetailDao) Descriptor() ([]byte, []int) {
	return file_privatemessage_proto_rawDescGZIP(), []int{7}
}

func (x *ReqPrivateMessageDetailDao) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ReqPrivateMessageDetailDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RspPrivateMessageDetailDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateMessage *PrivateMessageQueryDao `protobuf:"bytes,1,opt,name=privateMessage,proto3" json:"privateMessage,omitempty"`
	Content        string                  `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *RspPrivateMessageDetailDao) Reset() {
	*x = RspPrivateMessageDetailDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privatemessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPrivateMessageDetailDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPrivateMessageDetailDao) ProtoMessage() {}

func (x *RspPrivateMessageDetailDao) ProtoReflect() protoreflect.Message {
	mi := &file_privatemessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPrivateMessageDetailDao.ProtoReflect.Descriptor instead.
func (*RspPrivateMessageDetailDao) Descriptor() ([]byte, []int) {
	return file_privatemessage_proto_rawDescGZIP(), []int{8}
}

func (x *RspPrivateMessageDetailDao) GetPrivateMessage() *PrivateMessageQueryDao {
	if x != nil {
		return x.PrivateMessage
	}
	return nil
}

func (x *RspPrivateMessageDetailDao) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_privatemessage_proto protoreflect.FileDescriptor

var file_privatemessage_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf5, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x44, 0x61, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x29, 0x0a, 0x17, 0x52,
	0x73, 0x70, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x41, 0x64, 0x64, 0x44, 0x61, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x1a, 0x52, 0x65, 0x71, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x61, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x03, 0x69, 0x64, 0x73, 0x22, 0x52, 0x0a, 0x20, 0x52, 0x65, 0x71, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0xe5, 0x01, 0x0a, 0x19, 0x52, 0x65, 0x71,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x9d, 0x01, 0x0a, 0x19, 0x52, 0x73, 0x70, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x12, 0x3a,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x44, 0x61, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0xf8, 0x01, 0x0a, 0x16, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65,
	0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4a, 0x0a, 0x1a, 0x52,
	0x65, 0x71, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x1a, 0x52, 0x73, 0x70, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x44, 0x61, 0x6f, 0x12, 0x4e, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x52, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x32, 0xaa, 0x04, 0x0a, 0x11, 0x44, 0x61, 0x6f, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x68, 0x0a, 0x14, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x44, 0x61, 0x6f, 0x12, 0x27,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x52, 0x65, 0x71, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x41, 0x64, 0x64, 0x44, 0x61, 0x6f, 0x1a, 0x27, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x73, 0x70, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x44, 0x61, 0x6f,
	0x12, 0x69, 0x0a, 0x1d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x6f, 0x12, 0x30, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x5d, 0x0a, 0x17, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x12, 0x2a, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x61, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x6e, 0x0a, 0x16, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x44, 0x61, 0x6f, 0x12, 0x29, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x1a,
	0x29, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x52, 0x73, 0x70, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x6f, 0x12, 0x71, 0x0a, 0x17, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x44, 0x61, 0x6f, 0x12, 0x2a, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x61,
	0x6f, 0x1a, 0x2a, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x52, 0x73, 0x70, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x6f, 0x42, 0x40, 0x5a,
	0x3e, 0x62, 0x61, 0x62, 0x79, 0x2d, 0x66, 0x72, 0x69, 0x65, 0x64, 0x2d, 0x72, 0x69, 0x63, 0x65,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6b, 0x69,
	0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_privatemessage_proto_rawDescOnce sync.Once
	file_privatemessage_proto_rawDescData = file_privatemessage_proto_rawDesc
)

func file_privatemessage_proto_rawDescGZIP() []byte {
	file_privatemessage_proto_rawDescOnce.Do(func() {
		file_privatemessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_privatemessage_proto_rawDescData)
	})
	return file_privatemessage_proto_rawDescData
}

var file_privatemessage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_privatemessage_proto_goTypes = []interface{}{
	(*ReqPrivateMessageAddDao)(nil),          // 0: privatemessage.ReqPrivateMessageAddDao
	(*RspPrivateMessageAddDao)(nil),          // 1: privatemessage.RspPrivateMessageAddDao
	(*ReqPrivateMessageDeleteDao)(nil),       // 2: privatemessage.ReqPrivateMessageDeleteDao
	(*ReqPrivateMessageStatusUpdateDao)(nil), // 3: privatemessage.ReqPrivateMessageStatusUpdateDao
	(*ReqPrivateMessageQueryDao)(nil),        // 4: privatemessage.ReqPrivateMessageQueryDao
	(*RspPrivateMessageQueryDao)(nil),        // 5: privatemessage.RspPrivateMessageQueryDao
	(*PrivateMessageQueryDao)(nil),           // 6: privatemessage.PrivateMessageQueryDao
	(*ReqPrivateMessageDetailDao)(nil),       // 7: privatemessage.ReqPrivateMessageDetailDao
	(*RspPrivateMessageDetailDao)(nil),       // 8: privatemessage.RspPrivateMessageDetailDao
	(*emptypb.Empty)(nil),                    // 9: google.protobuf.Empty
}
var file_privatemessage_proto_depIdxs = []int32{
	6, // 0: privatemessage.RspPrivateMessageQueryDao.list:type_name -> privatemessage.PrivateMessageQueryDao
	6, // 1: privatemessage.RspPrivateMessageDetailDao.privateMessage:type_name -> privatemessage.PrivateMessageQueryDao
	0, // 2: privatemessage.DaoPrivateMessage.PrivateMessageAddDao:input_type -> privatemessage.ReqPrivateMessageAddDao
	3, // 3: privatemessage.DaoPrivateMessage.PrivateMessageStatusUpdateDao:input_type -> privatemessage.ReqPrivateMessageStatusUpdateDao
	2, // 4: privatemessage.DaoPrivateMessage.PrivateMessageDeleteDao:input_type -> privatemessage.ReqPrivateMessageDeleteDao
	4, // 5: privatemessage.DaoPrivateMessage.PrivateMessageQueryDao:input_type -> privatemessage.ReqPrivateMessageQueryDao
	7, // 6: privatemessage.DaoPrivateMessage.PrivateMessageDetailDao:input_type -> privatemessage.ReqPrivateMessageDetailDao
	1, // 7: privatemessage.DaoPrivateMessage.PrivateMessageAddDao:output_type -> privatemessage.RspPrivateMessageAddDao
	9, // 8: privatemessage.DaoPrivateMessage.PrivateMessageStatusUpdateDao:output_type -> google.protobuf.Empty
	9, // 9: privatemessage.DaoPrivateMessage.PrivateMessageDeleteDao:output_type -> google.protobuf.Empty
	5, // 10: privatemessage.DaoPrivateMessage.PrivateMessageQueryDao:output_type -> privatemessage.RspPrivateMessageQueryDao
	8, // 11: privatemessage.DaoPrivateMessage.PrivateMessageDetailDao:output_type -> privatemessage.RspPrivateMessageDetailDao
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_privatemessage_proto_init() }
func file_privatemessage_proto_init() {
	if File_privatemessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_privatemessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPrivateMessageAddDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privatemessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPrivateMessageAddDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privatemessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPrivateMessageDeleteDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privatemessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPrivateMessageStatusUpdateDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privatemessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPrivateMessageQueryDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privatemessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPrivateMessageQueryDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privatemessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivateMessageQueryDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privatemessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPrivateMessageDetailDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privatemessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPrivateMessageDetailDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_privatemessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_privatemessage_proto_goTypes,
		DependencyIndexes: file_privatemessage_proto_depIdxs,
		MessageInfos:      file_privatemessage_proto_msgTypes,
	}.Build()
	File_privatemessage_proto = out.File
	file_privatemessage_proto_rawDesc = nil
	file_privatemessage_proto_goTypes = nil
	file_privatemessage_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DaoPrivateMessageClient is the client API for DaoPrivateMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaoPrivateMessageClient interface {
	// 发送私信
	PrivateMessageAddDao(ctx context.Context, in *ReqPrivateMessageAddDao, opts ...grpc.CallOption) (*RspPrivateMessageAddDao, error)
	// 更新私信阅读状态
	PrivateMessageStatusUpdateDao(ctx context.Context, in *ReqPrivateMessageStatusUpdateDao, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除私信
	PrivateMessageDeleteDao(ctx context.Context, in *ReqPrivateMessageDeleteDao, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 查询私信列表
	PrivateMessageQueryDao(ctx context.Context, in *ReqPrivateMessageQueryDao, opts ...grpc.CallOption) (*RspPrivateMessageQueryDao, error)
	// 查询私信详情
	PrivateMessageDetailDao(ctx context.Context, in *ReqPrivateMessageDetailDao, opts ...grpc.CallOption) (*RspPrivateMessageDetailDao, error)
}

type daoPrivateMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewDaoPrivateMessageClient(cc grpc.ClientConnInterface) DaoPrivateMessageClient {
	return &daoPrivateMessageClient{cc}
}

func (c *daoPrivateMessageClient) PrivateMessageAddDao(ctx context.Context, in *ReqPrivateMessageAddDao, opts ...grpc.CallOption) (*RspPrivateMessageAddDao, error) {
	out := new(RspPrivateMessageAddDao)
	err := c.cc.Invoke(ctx, "/privatemessage.DaoPrivateMessage/PrivateMessageAddDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoPrivateMessageClient) PrivateMessageStatusUpdateDao(ctx context.Context, in *ReqPrivateMessageStatusUpdateDao, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/privatemessage.DaoPrivateMessage/PrivateMessageStatusUpdateDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoPrivateMessageClient) PrivateMessageDeleteDao(ctx context.Context, in *ReqPrivateMessageDeleteDao, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/privatemessage.DaoPrivateMessage/PrivateMessageDeleteDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoPrivateMessageClient) PrivateMessageQueryDao(ctx context.Context, in *ReqPrivateMessageQueryDao, opts ...grpc.CallOption) (*RspPrivateMessageQueryDao, error) {
	out := new(RspPrivateMessageQueryDao)
	err := c.cc.Invoke(ctx, "/privatemessage.DaoPrivateMessage/PrivateMessageQueryDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoPrivateMessageClient) PrivateMessageDetailDao(ctx context.Context, in *ReqPrivateMessageDetailDao, opts ...grpc.CallOption) (*RspPrivateMessageDetailDao, error) {
	out := new(RspPrivateMessageDetailDao)
	err := c.cc.Invoke(ctx, "/privatemessage.DaoPrivateMessage/PrivateMessageDetailDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaoPrivateMessageServer is the server API for DaoPrivateMessage service.
type DaoPrivateMessageServer interface {
	// 发送私信
	PrivateMessageAddDao(context.Context, *ReqPrivateMessageAddDao) (*RspPrivateMessageAddDao, error)
	// 更新私信阅读状态
	PrivateMessageStatusUpdateDao(context.Context, *ReqPrivateMessageStatusUpdateDao) (*emptypb.Empty, error)
	// 删除私信
	PrivateMessageDeleteDao(context.Context, *ReqPrivateMessageDeleteDao) (*emptypb.Empty, error)
	// 查询私信列表
	PrivateMessageQueryDao(context.Context, *ReqPrivateMessageQueryDao) (*RspPrivateMessageQueryDao, error)
	// 查询私信详情
	PrivateMessageDetailDao(context.Context, *ReqPrivateMessageDetailDao) (*RspPrivateMessageDetailDao, error)
}

// UnimplementedDaoPrivateMessageServer can be embedded to have forward compatible implementations.
type UnimplementedDaoPrivateMessageServer struct {
}

func (*UnimplementedDaoPrivateMessageServer) PrivateMessageAddDao(context.Context, *ReqPrivateMessageAddDao) (*RspPrivateMessageAddDao, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrivateMessageAddDao not implemented")
}
func (*UnimplementedDaoPrivateMessageServer) PrivateMessageStatusUpdateDao(context.Context, *ReqPrivateMessageStatusUpdateDao) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrivateMessageStatusUpdateDao not implemented")
}
func (*UnimplementedDaoPrivateMessageServer) PrivateMessageDeleteDao(context.Context, *ReqPrivateMessageDeleteDao) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrivateMessageDeleteDao not implemented")
}
func (*UnimplementedDaoPrivateMessageServer) PrivateMessageQueryDao(context.Context, *ReqPrivateMessageQueryDao) (*RspPrivateMessageQueryDao, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrivateMessageQueryDao not implemented")
}
func (*UnimplementedDaoPrivateMessageServer) PrivateMessageDetailDao(context.Context, *ReqPrivateMessageDetailDao) (*RspPrivateMessageDetailDao, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrivateMessageDetailDao not implemented")
}

func RegisterDaoPrivateMessageServer(s *grpc.Server, srv DaoPrivateMessageServer) {
	s.RegisterService(&_DaoPrivateMessage_serviceDesc, srv)
}

func _DaoPrivateMessage_PrivateMessageAddDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPrivateMessageAddDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoPrivateMessageServer).PrivateMessageAddDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/privatemessage.DaoPrivateMessage/PrivateMessageAddDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoPrivateMessageServer).PrivateMessageAddDao(ctx, req.(*ReqPrivateMessageAddDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoPrivateMessage_PrivateMessageStatusUpdateDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPrivateMessageStatusUpdateDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoPrivateMessageServer).PrivateMessageStatusUpdateDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/privatemessage.DaoPrivateMessage/PrivateMessageStatusUpdateDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoPrivateMessageServer).PrivateMessageStatusUpdateDao(ctx, req.(*ReqPrivateMessageStatusUpdateDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoPrivateMessage_PrivateMessageDeleteDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPrivateMessageDeleteDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoPrivateMessageServer).PrivateMessageDeleteDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/privatemessage.DaoPrivateMessage/PrivateMessageDeleteDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoPrivateMessageServer).PrivateMessageDeleteDao(ctx, req.(*ReqPrivateMessageDeleteDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoPrivateMessage_PrivateMessageQueryDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPrivateMessageQueryDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoPrivateMessageServer).PrivateMessageQueryDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/privatemessage.DaoPrivateMessage/PrivateMessageQueryDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoPrivateMessageServer).PrivateMessageQueryDao(ctx, req.(*ReqPrivateMessageQueryDao))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoPrivateMessage_PrivateMessageDetailDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPrivateMessageDetailDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoPrivateMessageServer).PrivateMessageDetailDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/privatemessage.DaoPrivateMessage/PrivateMessageDetailDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoPrivateMessageServer).PrivateMessageDetailDao(ctx, req.(*ReqPrivateMessageDetailDao))
	}
	return interceptor(ctx, in, info, handler)
}

var _DaoPrivateMessage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "privatemessage.DaoPrivateMessage",
	HandlerType: (*DaoPrivateMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrivateMessageAddDao",
			Handler:    _DaoPrivateMessage_PrivateMessageAddDao_Handler,
		},
		{
			MethodName: "PrivateMessageStatusUpdateDao",
			Handler:    _DaoPrivateMessage_PrivateMessageStatusUpdateDao_Handler,
		},
		{
			MethodName: "PrivateMessageDeleteDao",
			Handler:    _DaoPrivateMessage_PrivateMessageDeleteDao_Handler,
		},
		{
			MethodName: "PrivateMessageQueryDao",
			Handler:    _DaoPrivateMessage_PrivateMessageQueryDao_Handler,
		},
		{
			MethodName: "PrivateMessageDetailDao",
			Handler:    _DaoPrivateMessage_PrivateMessageDetailDao_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "privatemessage.proto",
}
