log:
  loglevel: "debug"
  logpath:

server:
  name: "root-account"
  serial: 1
  addr: "localhost"
  port: 18073

redis:
  redisurl: "localhost:26379"
  redispassword: "123456"
  redisdb: 9

etcd:
  - "http://localhost:23791"

healthyrolltime: 1000

servers:
  accountdaoserver: "account-dao"