log:
  loglevel: "debug"
  logpath:

server:
  addr: "localhost"
  port: 18073

redis:
  redisurl: "localhost:26379"
  redispassword: "123456"
  redisdb: 9

connect:
  accountdaourl: "http://localhost:18061"