log:
  loglevel: "debug"
  logpath: "/baby/logs/file.log"

server:
  httpserver:
    name: "file"
    serial: 1
    addr: "0.0.0.0"
    port: 8080
    register: "http://127.0.0.1:18050"

register:
  healthyrolltime: 3000
  etcd:
    cluster:
      - "http://etcd:2379"

messagequeue:
  consumetopics:
    deletefile:
      topic: "delete_file"
      channel: "delete_file_channel"
  nsq:
    cluster: nsq:4150

database:
  maindatabase:
    host: baby-mysql
    port: 3306
    username: root
    password: 123456
    dbname: baby-file