#postgresurl: postgres://postgres:ps4@localhost:5433/baby_fried_rice?sslmode=disable
postgresurl: postgres://postgres:zh.fei@116.62.36.208:3432/baby_fried_rice?sslmode=disable
redisurl: localhost:6379
#redisurl: 119.23.49.85:6379
redispassword:
redisdb: 3