log:
  loglevel: "debug"
  logpath:

server:
  name: "sms-dao"
  serial: 1
  addr: "0.0.0.0"
  port: 18065
  register: "http://127.0.0.1:18065"

redis:
  redisurl: "localhost:26379"
  redispassword: "123456"
  redisdb: 9

etcd:
  - "http://127.0.0.1:23791"

rpc:
  server:
    certfile: "cert/server.pem"
    keyfile: "cert/server.key"

healthyrolltime: 1000

mysqlurl: "root:123456@tcp(127.0.0.1:23306)/baby-sms?charset=utf8mb4&parseTime=True&loc=Local"

endpoint: ""
accesskeyid: ""
accesskeysecret: ""