// proto 文件版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.14.0
// source: user.proto

// 生成文件的包名

package user

import (
	common "baby-fried-rice/internal/pkg/kit/grpc/pbservices/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqUserRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    *ReqPasswordLogin `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Username string            `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Gender   bool              `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Phone    string            `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *ReqUserRegister) Reset() {
	*x = ReqUserRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserRegister) ProtoMessage() {}

func (x *ReqUserRegister) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserRegister.ProtoReflect.Descriptor instead.
func (*ReqUserRegister) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *ReqUserRegister) GetLogin() *ReqPasswordLogin {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *ReqUserRegister) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqUserRegister) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

func (x *ReqUserRegister) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ReqPasswordLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginName string `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip        string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *ReqPasswordLogin) Reset() {
	*x = ReqPasswordLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPasswordLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPasswordLogin) ProtoMessage() {}

func (x *ReqPasswordLogin) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPasswordLogin.ProtoReflect.Descriptor instead.
func (*ReqPasswordLogin) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *ReqPasswordLogin) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *ReqPasswordLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqPasswordLogin) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// 定义登录函数输入参数
type ReqUserLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *ReqUserLogin) Reset() {
	*x = ReqUserLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserLogin) ProtoMessage() {}

func (x *ReqUserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserLogin.ProtoReflect.Descriptor instead.
func (*ReqUserLogin) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *ReqUserLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqUserLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RspDaoUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	LoginName string `protobuf:"bytes,2,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Username  string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	SchoolId  string `protobuf:"bytes,4,opt,name=schoolId,proto3" json:"schoolId,omitempty"`
	Gender    bool   `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Age       int64  `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	Phone     string `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *RspDaoUser) Reset() {
	*x = RspDaoUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspDaoUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspDaoUser) ProtoMessage() {}

func (x *RspDaoUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspDaoUser.ProtoReflect.Descriptor instead.
func (*RspDaoUser) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *RspDaoUser) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RspDaoUser) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *RspDaoUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RspDaoUser) GetSchoolId() string {
	if x != nil {
		return x.SchoolId
	}
	return ""
}

func (x *RspDaoUser) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

func (x *RspDaoUser) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RspDaoUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// 定义登录函数返回参数
type RspDaoUserLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *RspDaoUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *RspDaoUserLogin) Reset() {
	*x = RspDaoUserLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspDaoUserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspDaoUserLogin) ProtoMessage() {}

func (x *RspDaoUserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspDaoUserLogin.ProtoReflect.Descriptor instead.
func (*RspDaoUserLogin) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *RspDaoUserLogin) GetUser() *RspDaoUser {
	if x != nil {
		return x.User
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

var file_user_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x89, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x5c, 0x0a, 0x10,
	0x52, 0x65, 0x71, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x46, 0x0a, 0x0c, 0x52, 0x65,
	0x71, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0xc0, 0x01, 0x0a, 0x0a, 0x52, 0x73, 0x70, 0x44, 0x61, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x63, 0x68,
	0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x63, 0x68,
	0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x52, 0x73, 0x70, 0x44, 0x61, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x73,
	0x70, 0x44, 0x61, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x32, 0x8a,
	0x01, 0x0a, 0x07, 0x44, 0x61, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0f, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x61, 0x6f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x15, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0c,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x6f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x73, 0x70, 0x44,
	0x61, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x37, 0x5a, 0x35, 0x62,
	0x61, 0x62, 0x79, 0x2d, 0x66, 0x72, 0x69, 0x65, 0x64, 0x2d, 0x72, 0x69, 0x63, 0x65, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6b, 0x69, 0x74, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData = file_user_proto_rawDesc
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_proto_rawDescData)
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_proto_goTypes = []interface{}{
	(*ReqUserRegister)(nil),       // 0: user.ReqUserRegister
	(*ReqPasswordLogin)(nil),      // 1: user.ReqPasswordLogin
	(*ReqUserLogin)(nil),          // 2: user.ReqUserLogin
	(*RspDaoUser)(nil),            // 3: user.RspDaoUser
	(*RspDaoUserLogin)(nil),       // 4: user.RspDaoUserLogin
	(*common.CommonResponse)(nil), // 5: common.CommonResponse
}
var file_user_proto_depIdxs = []int32{
	1, // 0: user.ReqUserRegister.login:type_name -> user.ReqPasswordLogin
	3, // 1: user.RspDaoUserLogin.user:type_name -> user.RspDaoUser
	0, // 2: user.DaoUser.UserDaoRegister:input_type -> user.ReqUserRegister
	1, // 3: user.DaoUser.UserDaoLogin:input_type -> user.ReqPasswordLogin
	5, // 4: user.DaoUser.UserDaoRegister:output_type -> common.CommonResponse
	4, // 5: user.DaoUser.UserDaoLogin:output_type -> user.RspDaoUserLogin
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPasswordLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspDaoUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspDaoUserLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_rawDesc = nil
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DaoUserClient is the client API for DaoUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaoUserClient interface {
	// 用户注册函数
	UserDaoRegister(ctx context.Context, in *ReqUserRegister, opts ...grpc.CallOption) (*common.CommonResponse, error)
	//用户登录函数
	UserDaoLogin(ctx context.Context, in *ReqPasswordLogin, opts ...grpc.CallOption) (*RspDaoUserLogin, error)
}

type daoUserClient struct {
	cc grpc.ClientConnInterface
}

func NewDaoUserClient(cc grpc.ClientConnInterface) DaoUserClient {
	return &daoUserClient{cc}
}

func (c *daoUserClient) UserDaoRegister(ctx context.Context, in *ReqUserRegister, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, "/user.DaoUser/UserDaoRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daoUserClient) UserDaoLogin(ctx context.Context, in *ReqPasswordLogin, opts ...grpc.CallOption) (*RspDaoUserLogin, error) {
	out := new(RspDaoUserLogin)
	err := c.cc.Invoke(ctx, "/user.DaoUser/UserDaoLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaoUserServer is the server API for DaoUser service.
type DaoUserServer interface {
	// 用户注册函数
	UserDaoRegister(context.Context, *ReqUserRegister) (*common.CommonResponse, error)
	//用户登录函数
	UserDaoLogin(context.Context, *ReqPasswordLogin) (*RspDaoUserLogin, error)
}

// UnimplementedDaoUserServer can be embedded to have forward compatible implementations.
type UnimplementedDaoUserServer struct {
}

func (*UnimplementedDaoUserServer) UserDaoRegister(context.Context, *ReqUserRegister) (*common.CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserDaoRegister not implemented")
}
func (*UnimplementedDaoUserServer) UserDaoLogin(context.Context, *ReqPasswordLogin) (*RspDaoUserLogin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserDaoLogin not implemented")
}

func RegisterDaoUserServer(s *grpc.Server, srv DaoUserServer) {
	s.RegisterService(&_DaoUser_serviceDesc, srv)
}

func _DaoUser_UserDaoRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqUserRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoUserServer).UserDaoRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoUser/UserDaoRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoUserServer).UserDaoRegister(ctx, req.(*ReqUserRegister))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaoUser_UserDaoLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPasswordLogin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoUserServer).UserDaoLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DaoUser/UserDaoLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoUserServer).UserDaoLogin(ctx, req.(*ReqPasswordLogin))
	}
	return interceptor(ctx, in, info, handler)
}

var _DaoUser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.DaoUser",
	HandlerType: (*DaoUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserDaoRegister",
			Handler:    _DaoUser_UserDaoRegister_Handler,
		},
		{
			MethodName: "UserDaoLogin",
			Handler:    _DaoUser_UserDaoLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
