log:
  loglevel: "debug"
  logpath: "/baby/logs/gateway.log"

server:
  name: "gateway"
  serial: 1
  addr: "0.0.0.0"
  port: 8080

redis:
  redisurl: "redis:6379"
  redispassword: "123456"
  redisdb: 9

etcd:
  - "http://etcd:2379"

servers:
  useraccountserver: "user-account"
  backendserver: "root-account"