log:
  loglevel: "debug"
  logpath: "/baby/logs/space.log"

server:
  name: "space-service"
  addr: "0.0.0.0"
  serial: 1
  port: 8080
  register: "http://127.0.0.1:18074"

redis:
  redisurl: "redis:6379"
  redispassword: "123456"
  redisdb: 9

etcd:
  - "http://etcd:2379"

rpc:
  client:
    certfile: "cert/server.pem"

servers:
  spacedaoserver: "space-dao"
  accountdaoserver: "account-dao"

nsq:
  addr: nsqd:4150
  topic: baby-test