log:
  loglevel: "debug"
  logpath: "/baby/logs/im.log"

server:
  name: "im-service"
  serial: 1
  addr: "0.0.0.0"
  port: 8080
  register: "http://127.0.0.1:18076"

etcd:
  - "http://etcd:2379"

rpc:
  client:
    certfile: "cert/server.pem"

healthyrolltime: 1000

servers:
  accountdaoserver: "account-dao"
  imdaoserver: "im-dao"