log:
  loglevel: "debug"
  logpath:

server:
  httpserver:
    name: "manage"
    serial: 1
    addr: "0.0.0.0"
    port: 18073
    register: "http://127.0.0.1:18073"

cache:
  redis:
    maincache:
      addr: "localhost:26379"
      password: "123456"
      db: 9

register:
  healthyrolltime: 3000
  etcd:
    cluster:
      - "http://127.0.0.1:23791"

messagequeue:
  consumetopics:
    deletefile:
      topic: "baby-delete-file"
      channel: "baby-delete-file-channel"
  nsq:
    cluster: 127.0.0.1:4150

database:
  subdatabase:
    accountdatabase:
      host: 127.0.0.1
      port: 23306
      username: root
      password: 123456
      dbname: baby-account
    shopdatabase:
      host: 127.0.0.1
      port: 23306
      username: root
      password: 123456
      dbname: baby-shop
    smsdatabase:
      host: 127.0.0.1
      port: 23306
      username: root
      password: 123456
      dbname: baby-sms