log:
  loglevel: "debug"
  logpath:

server:
  name: "manage"
  serial: 1
  addr: "0.0.0.0"
  port: 18073
  register: "http://127.0.0.1:18073"

redis:
  redisurl: "localhost:26379"
  redispassword: "123456"
  redisdb: 9

etcd:
  - "http://localhost:23791"

healthyrolltime: 1000

mysqls:
  account: "root:123456@tcp(127.0.0.1:23306)/baby-account?charset=utf8mb4&parseTime=True&loc=Local"
  shop: "root:123456@tcp(127.0.0.1:23306)/baby-shop?charset=utf8mb4&parseTime=True&loc=Local"
  sms: "root:123456@tcp(127.0.0.1:23306)/baby-sms?charset=utf8mb4&parseTime=True&loc=Local"