log:
  loglevel: "debug"
  logpath:

server:
  httpserver:
    name: "gateway"
    serial: 1
    addr: "0.0.0.0"
    port: 18070
    certfile: "./cert/server.pem"
    keyfile: "./cert/server.key"

cache:
  redis:
    maincache:
      addr: "localhost:26379"
      password: "123456"
      db: 9

register:
  healthyrolltime: 3000
  etcd:
    cluster:
      - "http://127.0.0.1:23791"

rpc:
  subservers:
    manageserver: "manage"
    useraccountserver: "user-account"
    spaceserver: "space-service"
    connectserver: "connect"
    imserver: "im-service"
    fileserver: "file"
    shopserver: "shop-service"
    liveserver: "live-service"
    blogserver: "blog-service"