log:
  loglevel: "debug"
  logpath:

server:
  name: "gateway"
  serial: 1
  addr: "0.0.0.0"
  port: 18070

redis:
  redisurl: "localhost:26379"
  redispassword: "123456"
  redisdb: 9

etcd:
  - "http://127.0.0.1:23791"

servers:
  backend: "backend"
  useraccountserver: "user-account"
  spaceserver: "space-service"
  connectserver: "connect"
  imserver: "im-service"
  fileserver: "file"