log:
  loglevel: "debug"
  logpath:

server:
  name: "gateway"
  addr: "localhost"
  port: 18070

redis:
  redisurl: "localhost:26379"
  redispassword:
  redisdb: 9

connect:
  rooturl: "localhost:18073"
